github.com/RhysU/ar: ar::predictor< Value, Index > Class Template Reference
ar::predictor< Value, Index > Class Template Reference
Simulate an autoregressive model process with an InputIterator interface.
#include <ar.hpp>
Public Types
typedef std::input_iterator_tag iterator_category
typedef Value value_type
typedef std::ptrdiff_t difference_type
typedef const Value * pointer
typedef const Value & reference
Public Member Functions
predictor (Index n=0)
Singular instance marking prediction index n.
template<class RandomAccessIterator >
predictor (RandomAccessIterator params_first, RandomAccessIterator params_last)
Iterate on the process \(x_n + a_1 x_{n - 1} + \dots + a_p x_{n - p} = 0\).
template<class RandomAccessIterator , class NoiseGenerator >
predictor (RandomAccessIterator params_first, RandomAccessIterator params_last, NoiseGenerator generator)
Iterate on the process \(x_n + a_1 x_{n - 1} + \dots + a_p x_{n - p} = \epsilon_n\) given zero initial conditions.
predictor (const predictor &other)
Copy constructor.
predictor & operator= (const predictor &other)
Assignment operator.
~predictor ()
Destructor.
template<class InputIterator >
predictor & initial_conditions (InputIterator initial_first, const Value x0adjust=0)
Specify process initial conditions \(x_{n-1}, \dots, x_{n-p}\) where \(p\) is the process order fixed by the constructor.
predictor & operator++ ()
Prefix increment.
predictor operator++ (int)
Postfix increment.
reference operator* () const
Obtain the process prediction \(x_n\).
bool operator== (const predictor &other) const
Check if two iterators represent the same simulation time.
bool operator!= (const predictor &other) const
Check if two iterators represent different simulation times.
Detailed Description
template<typename Value, typename Index = std::size_t>
class ar::predictor< Value, Index >
Simulate an autoregressive model process with an InputIterator interface.
Definition at line 820 of file ar.hpp.
Member Typedef Documentation
difference_type
template<typename Value , typename Index = std::size_t> typedef std::ptrdiff_t ar::predictor< Value, Index >::difference_type
Definition at line 825 of file ar.hpp.
iterator_category
template<typename Value , typename Index = std::size_t> typedef std::input_iterator_tag ar::predictor< Value, Index >::iterator_category
Definition at line 823 of file ar.hpp.
pointer
template<typename Value , typename Index = std::size_t> typedef const Value* ar::predictor< Value, Index >::pointer
Definition at line 826 of file ar.hpp.
reference
template<typename Value , typename Index = std::size_t> typedef const Value& ar::predictor< Value, Index >::reference
Definition at line 827 of file ar.hpp.
value_type
template<typename Value , typename Index = std::size_t> typedef Value ar::predictor< Value, Index >::value_type
Definition at line 824 of file ar.hpp.
Constructor & Destructor Documentation
predictor() [1/4]
template<typename Value , typename Index = std::size_t> ar::predictor< Value, Index >::predictor (Index n = 0) inline explicit
Singular instance marking prediction index n.
Definition at line 830 of file ar.hpp.
predictor() [2/4]
template<typename Value , typename Index = std::size_t> template<class RandomAccessIterator > ar::predictor< Value, Index >::predictor (RandomAccessIterator params_first, RandomAccessIterator params_last) inline
Iterate on the process \(x_n + a_1 x_{n - 1} + \dots + a_p x_{n - p} = 0\).
Presumably initial_conditions will be used to specify some initial state as otherwise the process is identically zero. The process order \(p\) is set by std::distance(params_first, params_last).
Parameters
params_first Beginning of the process parameter range starting with \(a_1\).
params_last End of the process parameter range.
Definition at line 851 of file ar.hpp.
References ar::negative_half_reflection_coefficient().
predictor() [3/4]
template<typename Value , typename Index = std::size_t> template<class RandomAccessIterator , class NoiseGenerator > ar::predictor< Value, Index >::predictor (RandomAccessIterator params_first, RandomAccessIterator params_last, NoiseGenerator generator) inline
Iterate on the process \(x_n + a_1 x_{n - 1} + \dots + a_p x_{n - p} = \epsilon_n\) given zero initial conditions.
The process order \(p\) is set by std::distance(params_first,params_last). The class std::tr1::variate_generator may be helpful in constructing normally distributed input.
Parameters
params_first Beginning of the process parameter range starting with \(a_1\).
params_last End of the process parameter range.
generator A nullary callback for generating \(\epsilon_n\). For example, a random number generator distributed like \(N\left(0, \sigma^2_\epsilon\right)\).
Definition at line 882 of file ar.hpp.
References ar::negative_half_reflection_coefficient().
predictor() [4/4]
template<typename Value , typename Index = std::size_t> ar::predictor< Value, Index >::predictor (const predictor< Value, Index > & other) inline
Copy constructor.
Definition at line 899 of file ar.hpp.
~predictor()
template<typename Value , typename Index = std::size_t> ar::predictor< Value, Index >::~predictor () inline
Destructor.
Definition at line 931 of file ar.hpp.
Member Function Documentation
initial_conditions()
template<typename Value , typename Index = std::size_t> template<class InputIterator > predictor & ar::predictor< Value, Index >::initial_conditions (InputIterator initial_first, const Value x0adjust = 0) inline
Specify process initial conditions \(x_{n-1}, \dots, x_{n-p}\) where \(p\) is the process order fixed by the constructor.
The simulation index \(n\) is reset to zero and, optionally, \(x_0\) is additively adjusted by x0adjust.
Parameters
initial_first Beginning of the initial condition range \(x_{n-1}, \dots, x_{n-p}\) which must contain \(p\) values.
x0adjust An additive adjustment made to \(\epsilon_0\).
Definition at line 948 of file ar.hpp.
References ar::negative_half_reflection_coefficient().
operator!=()
template<typename Value , typename Index = std::size_t> bool ar::predictor< Value, Index >::operator!= (const predictor< Value, Index > & other) const inline
Check if two iterators represent different simulation times.
Definition at line 1036 of file ar.hpp.
References ar::negative_half_reflection_coefficient().
operator*()
template<typename Value , typename Index = std::size_t> reference ar::predictor< Value, Index >::operator* () const inline
Obtain the process prediction \(x_n\).
Definition at line 1022 of file ar.hpp.
operator++() [1/2]
template<typename Value , typename Index = std::size_t> predictor & ar::predictor< Value, Index >::operator++ () inline
Prefix increment.
Definition at line 972 of file ar.hpp.
References ar::negative_half_reflection_coefficient().
operator++() [2/2]
template<typename Value , typename Index = std::size_t> predictor ar::predictor< Value, Index >::operator++ (int) inline
Postfix increment.
Definition at line 1014 of file ar.hpp.
operator=()
template<typename Value , typename Index = std::size_t> predictor & ar::predictor< Value, Index >::operator= (const predictor< Value, Index > & other) inline
Assignment operator.
Definition at line 907 of file ar.hpp.
References ar::negative_half_reflection_coefficient().
operator==()
template<typename Value , typename Index = std::size_t> bool ar::predictor< Value, Index >::operator== (const predictor< Value, Index > & other) const inline
Check if two iterators represent the same simulation time.
Definition at line 1030 of file ar.hpp.
References ar::negative_half_reflection_coefficient().
The documentation for this class was generated from the following file:
ar.hpp